languageCode: zh
defaultContentLanguage: zh
title: Graph Code Gallery

googleAnalytics: G-J3NCP3DPFH

disableKinds:
- taxonomyTerm

# Code higlighting settings
pygmentsCodefences: true
pygmentsCodeFencesGuesSsyntax: false
pygmentsOptions: ""
pygmentsStyle: "monokai"
pygmentsUseClasses: false

markup:
  goldmark:
    parser:
      autoHeadingIDType: "github-ascii"
    renderer:
      unsafe: true

module: 
  imports:
  - path: github.com/bep/docuapi/v2

params:
  search: true
  maxMenuDepth: 3 
  language_tabs:
  - key: python
    name: python

languages:
  en:
    languageName: English
    weight: 1
  zh:
    languageName: 简体中文
    weight: 2
